name: 🤖 Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  dependabot:
    name: 🤖 Dependabot PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run tests
        run: npm test -- --watchAll=false

      - name: 🔧 Build project
        run: npm run build

      - name: 🤖 Auto-merge Dependabot PR
        if: github.actor == 'dependabot[bot]'
        run: |
          echo "Dependabot PR detected, but auto-merge is disabled for manual review"
          echo "Please review and merge manually if tests pass"
