name: 🛡️ Setup Branch Protection

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [ main ]
    paths: [ '.github/workflows/setup-branch-protection.yml' ]

jobs:
  setup-branch-protection:
    name: 🛡️ Setup Branch Protection
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Branch Protection for main
        uses: benjefferies/branch-protection-bot@master
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          enforce_admins: true
          required_status_checks: true
          required_status_checks_contexts: |
            code-quality
            test
            build
            security-audit
          dismiss_stale_reviews: true
          require_code_owner_reviews: true
          required_approving_review_count: 1
          require_last_push_approval: false
          restrictions: null
          allow_force_pushes: false
          allow_deletions: false

      - name: 🔧 Setup Branch Protection for develop
        uses: benjefferies/branch-protection-bot@master
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: develop
          enforce_admins: true
          required_status_checks: true
          required_status_checks_contexts: |
            code-quality
            test
            build
          dismiss_stale_reviews: true
          require_code_owner_reviews: true
          required_approving_review_count: 1
          require_last_push_approval: false
          restrictions: null
          allow_force_pushes: false
          allow_deletions: false

      - name: ✅ Branch Protection Setup Complete
        run: |
          echo "🛡️ Branch protection has been configured for main and develop branches"
          echo "📋 Protection rules applied:"
          echo "  - Require status checks before merging"
          echo "  - Require code owner reviews"
          echo "  - Require up-to-date branches"
          echo "  - Dismiss stale reviews"
          echo "  - Restrict force pushes"
          echo "  - Restrict branch deletion"
