name: 🛡️ Setup Branch Protection

on:
  workflow_dispatch: # Manual trigger

jobs:
  setup-branch-protection:
    name: 🛡️ Setup Branch Protection
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      statuses: write
      repository-projects: write
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Branch Protection using GitHub CLI
        run: |
          echo "🛡️ Setting up branch protection rules using GitHub CLI..."
          
          # Check if branch protection already exists
          if gh api repos/${{ github.repository }}/branches/main/protection >/dev/null 2>&1; then
            echo "ℹ️  Branch protection already exists for main branch"
          else
            echo "🔧 Configuring main branch protection..."
            gh api repos/${{ github.repository }}/branches/main/protection \
              --method PUT \
              --field required_status_checks='{"strict":true,"contexts":["code-quality","test","build","security-audit"]}' \
              --field enforce_admins=true \
              --field required_pull_request_reviews='{"required_approving_review_count":1,"dismiss_stale_reviews":true,"require_code_owner_reviews":true}' \
              --field restrictions=null \
              --field allow_force_pushes=false \
              --field allow_deletions=false || {
                echo "⚠️  Failed to configure main branch protection. This might require manual setup."
                echo "📋 Please follow the instructions in .github/BRANCH_PROTECTION.md"
                exit 0
              }
            echo "✅ Main branch protection configured successfully"
          fi
          
          # Check if develop branch exists and configure protection
          if gh api repos/${{ github.repository }}/branches/develop >/dev/null 2>&1; then
            if gh api repos/${{ github.repository }}/branches/develop/protection >/dev/null 2>&1; then
              echo "ℹ️  Branch protection already exists for develop branch"
            else
              echo "🔧 Configuring develop branch protection..."
              gh api repos/${{ github.repository }}/branches/develop/protection \
                --method PUT \
                --field required_status_checks='{"strict":true,"contexts":["code-quality","test","build"]}' \
                --field enforce_admins=true \
                --field required_pull_request_reviews='{"required_approving_review_count":1,"dismiss_stale_reviews":true,"require_code_owner_reviews":true}' \
                --field restrictions=null \
                --field allow_force_pushes=false \
                --field allow_deletions=false || {
                  echo "⚠️  Failed to configure develop branch protection. This might require manual setup."
                  echo "📋 Please follow the instructions in .github/BRANCH_PROTECTION.md"
                  exit 0
                }
              echo "✅ Develop branch protection configured successfully"
            fi
          else
            echo "ℹ️  Develop branch doesn't exist, skipping..."
          fi

      - name: ✅ Branch Protection Setup Complete
        run: |
          echo ""
          echo "🎉 Branch protection setup complete!"
          echo ""
          echo "📋 Protection rules applied:"
          echo "  - Require status checks before merging"
          echo "  - Require code owner reviews"
          echo "  - Require up-to-date branches"
          echo "  - Dismiss stale reviews"
          echo "  - Restrict force pushes"
          echo "  - Restrict branch deletion"
          echo ""
          echo "🛡️ Your branches are now protected!"
          echo ""
          echo "📖 For manual setup instructions, see: .github/BRANCH_PROTECTION.md"
